version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: energy_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: energy
    ports:
      - "5432:5432"